#poetry run pre-commit run --all-files

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

# Commitizen for conventional commit messages
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.4
    hooks:
    -   id: commitizen
        stages: [commit-msg]


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        additional_dependencies: 
            - types-PyYAML==6.0.12.20240917
            - types-setuptools
        args: ["--config-file=pyproject.toml"]
        exclude: ^tests/
